"""
Jupyterlab-pyflyby extension related test

Some of these test do not need the full extension installed so we put them here.
"""

import comm
from   comm.base_comm           import BaseComm, CommManager
from   pyflyby                  import _comms
from   pyflyby._comms           import (FORMATTING_IMPORTS, MISSING_IMPORTS,
                                        TIDY_IMPORTS, _reformat_helper,
                                        _register_target, comm_open_handler,
                                        extract_import_statements,
                                        pyflyby_comm_targets, remove_comms,
                                        run_tidy_imports, send_comm_message)
import pytest
import types
import uuid


# insert between marker
a = (
    """
import before as   b
# THIS CELL WAS AUTO-GENERATED BY PYFLYBY
import middle as m

# END AUTO-GENERATED BLOCK
import after as  f

""",
    "import numpy as np",
    """
import before as b
# THIS CELL WAS AUTO-GENERATED BY PYFLYBY
import middle as m
import numpy as np

# END AUTO-GENERATED BLOCK
import after as f

""",
)

# there are no markers
b = (
    """
""",
    "import numpy as np",
    """
import numpy as np

""",
)

# import exists before marker, but will still be inserted.
# this is non optimal, but expected if the cell has not been executed
c = (
    """
import numpy as np
# THIS CELL WAS AUTO-GENERATED BY PYFLYBY
# END AUTO-GENERATED BLOCK

""",
    "import numpy as np",
    """
import numpy as np
# THIS CELL WAS AUTO-GENERATED BY PYFLYBY

import numpy as np

# END AUTO-GENERATED BLOCK

""",
)


@pytest.mark.parametrize(
    "origin,imports,expected",
    [a, b, c],
)
def test_reformat_with_markers(origin, imports, expected):
    """
    Here we test that import are added to code between markers, and
    that before/after markers are properly reformatted.
    """
    assert str(_reformat_helper(origin, ["import numpy as np"])) == expected

code_block = """
from os import *
print(getcwd())

from deshaw.djs import Chart, TidyReport
from deshaw.djs import Chart
Chart(range(10)).show()
"""

expected_output = """
from os import getcwd
print(getcwd())

from deshaw.djs import Chart
Chart(range(10)).show()
"""

@pytest.mark.parametrize(
    "code_block",
    [code_block]
)
def test_tidy_imports(code_block):
    code_post_tidy_imports = run_tidy_imports(code_block)
    assert code_post_tidy_imports == expected_output


# ---------------------------------------------------------------------------
# Helpers / fixtures for the comm-handling tests below.
# ---------------------------------------------------------------------------

# These tests drive the handlers through the real comm machinery: the
# ``CommManager`` a kernel installs and the ``BaseComm`` it creates.  Only the
# iopub socket is replaced.  See https://github.com/deshaw/pyflyby/issues/598.


class RecordingComm(BaseComm):
    """A kernel-side comm that records what it publishes to the frontend."""

    def __init__(self, *args, **kwargs):
        self.published = []
        super().__init__(*args, **kwargs)

    def publish_msg(self, msg_type, data=None, **keys):
        self.published.append((msg_type, data))

    @property
    def sent(self):
        return [data for msg_type, data in self.published
                if msg_type == "comm_msg"]

    @property
    def closed(self):
        return any(msg_type == "comm_close" for msg_type, _ in self.published)


def _message(comm_id, **content):
    """The part of a kernel message that the comm manager reads."""
    return {"content": dict(content, comm_id=comm_id)}


class Frontend:
    """Sends comm messages to the kernel the way jupyterlab-pyflyby does."""

    def __init__(self, comm_manager):
        self.comm_manager = comm_manager

    def open(self, target_name):
        comm_id = uuid.uuid4().hex
        self.comm_manager.comm_open(
            None, None, _message(comm_id, target_name=target_name))
        return self.comm_manager.comms[comm_id]

    def send(self, comm, data):
        self.comm_manager.comm_msg(
            None, None, _message(comm.comm_id, data=data))

    def close(self, comm):
        self.comm_manager.comm_close(None, None, _message(comm.comm_id))


@pytest.fixture
def clean_comms():
    """Isolate the module-global ``comms`` registry for each test."""
    saved = dict(_comms.comms)
    _comms.comms.clear()
    try:
        yield _comms.comms
    finally:
        _comms.comms.clear()
        _comms.comms.update(saved)


@pytest.fixture
def frontend(monkeypatch, clean_comms, caplog):
    """A frontend talking to pyflyby through a real kernel-side comm manager."""
    comm_manager = CommManager()
    # ``in_jupyter`` looks for kernel.comm_manager, and ``handle_msg`` triggers
    # the shell's pre_execute/post_execute events around every comm message.
    shell = types.SimpleNamespace(
        kernel=types.SimpleNamespace(comm_manager=comm_manager),
        events=types.SimpleNamespace(trigger=lambda event: None))

    import IPython.core.getipython as getipython
    monkeypatch.setattr(getipython, "get_ipython", lambda: shell)
    monkeypatch.setattr(comm, "create_comm", RecordingComm)
    monkeypatch.setattr(comm, "get_comm_manager", lambda: comm_manager)

    for target_name in pyflyby_comm_targets:
        _register_target(target_name)

    yield Frontend(comm_manager)

    # CommManager catches whatever a handler raises and only logs it, so a
    # handler that fails outright can leave the assertions above intact.
    assert [record.getMessage() for record in caplog.get_records("call")
            if record.name == "Comm"] == []


# ---------------------------------------------------------------------------
# extract_import_statements
# ---------------------------------------------------------------------------


def test_extract_import_statements_separates_imports_and_code():
    code = "import os\nimport sys\nx = os.getcwd()\nprint(sys.path)\n"
    imports, remaining = extract_import_statements(code)
    assert imports == "import os\nimport sys"
    assert remaining == "\nx = os.getcwd()\nprint(sys.path)"


def test_extract_import_statements_reorders_imports():
    # ``SourceToSourceFileImportsTransformation`` re-orders imports.
    code = "import sys\nimport os\n"
    imports, remaining = extract_import_statements(code)
    assert imports == "import os\nimport sys"
    assert remaining.strip() == ""


def test_extract_import_statements_no_imports():
    code = "x = 1\ny = 2\n"
    imports, remaining = extract_import_statements(code)
    assert imports == ""
    assert "x = 1" in remaining
    assert "y = 2" in remaining


def test_extract_import_statements_syntax_error():
    # Magic commands and other non-Python lines raise SyntaxError.
    with pytest.raises(SyntaxError):
        extract_import_statements("%matplotlib inline\n")


# ---------------------------------------------------------------------------
# _register_target
# ---------------------------------------------------------------------------


def test_register_target(frontend):
    assert frontend.comm_manager.targets == {
        target_name: comm_open_handler for target_name in pyflyby_comm_targets
    }


# ---------------------------------------------------------------------------
# comm_open_handler
# ---------------------------------------------------------------------------


def test_comm_open_registers_comm(frontend, clean_comms):
    opened = frontend.open(FORMATTING_IMPORTS)

    assert clean_comms == {FORMATTING_IMPORTS: opened}


def test_comm_open_formatting_imports(frontend, clean_comms):
    opened = frontend.open(FORMATTING_IMPORTS)

    frontend.send(opened, {
        "type": FORMATTING_IMPORTS,
        "input_code": "import os\nos.getcwd()",
        "imports": ["import sys"],
        "msg_id": "m1",
    })

    assert opened.sent == [
        {
            "msg_id": "m1",
            "formatted_code": "import os\nimport sys\nos.getcwd()\n",
            "type": FORMATTING_IMPORTS,
        }
    ]


def test_comm_open_tidy_imports(frontend, clean_comms):
    opened = frontend.open(TIDY_IMPORTS)

    cells = [
        {"type": "code", "text": "import os\nimport sys\nos.getcwd()"},
        {"type": "code", "text": "%magic line"},
        {"type": "markdown", "text": "hello"},
    ]
    frontend.send(opened, {
        "type": TIDY_IMPORTS, "cellArray": cells, "checksum": "abc"})

    assert len(opened.sent) == 1
    reply = opened.sent[0]
    assert reply["type"] == TIDY_IMPORTS
    assert reply["checksum"] == "abc"
    # ``import sys`` is unused and dropped from the tidied imports.
    assert "import os" in reply["imports"]
    assert "import sys" not in reply["imports"]
    # The cell with a magic command raises SyntaxError and is flagged ignore.
    processed = reply["cells"]
    assert processed[0]["ignore"] is False
    assert processed[1]["ignore"] is True
    assert processed[1]["text"] == "%magic line"
    # Non-code cells are passed through untouched and never ignored.
    assert processed[2] == {"text": "hello", "type": "markdown", "ignore": False}


# ---------------------------------------------------------------------------
# comm_close_handler
# ---------------------------------------------------------------------------


def test_comm_close_stops_sending_to_closed_comm(frontend, clean_comms):
    opened = frontend.open(MISSING_IMPORTS)
    send_comm_message(MISSING_IMPORTS, {"missing_imports": "import numpy"})

    frontend.close(opened)
    send_comm_message(MISSING_IMPORTS, {"missing_imports": "import pandas"})

    assert clean_comms == {}
    assert opened.sent == [
        {"missing_imports": "import numpy", "type": MISSING_IMPORTS}]


def test_comm_close_keeps_other_comms(frontend, clean_comms):
    kept = frontend.open(FORMATTING_IMPORTS)

    frontend.close(frontend.open(TIDY_IMPORTS))

    assert clean_comms == {FORMATTING_IMPORTS: kept}


def test_comm_close_keeps_reopened_comm(frontend, clean_comms):
    # Reopening a target without closing the old comm replaces what is
    # registered for it; closing the old comm then matches nothing.
    old = frontend.open(TIDY_IMPORTS)
    new = frontend.open(TIDY_IMPORTS)

    frontend.close(old)

    assert clean_comms == {TIDY_IMPORTS: new}


# ---------------------------------------------------------------------------
# remove_comms
# ---------------------------------------------------------------------------


def test_remove_comms_closes_and_forgets(frontend, clean_comms):
    # Called when the extension is unloaded.
    opened = [frontend.open(target_name)
              for target_name in (FORMATTING_IMPORTS, TIDY_IMPORTS)]

    remove_comms()

    assert clean_comms == {}
    assert [comm.closed for comm in opened] == [True, True]
