#!/bin/bash -e

# License for THIS FILE ONLY: CC0 Public Domain Dedication
# http://creativecommons.org/publicdomain/zero/1.0/

PATH="$(dirname $(readlink -e $0)):$PATH"

if [[ -t 1 ]]; then
    diff -u "$@" | diff-colorize
else
    diff -u "$@"
fi
